# Netlify Configuration
[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.vercel.app"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.vercel.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200